name: nexus-os
description: Nexus OS - Ambiente de Desenvolvimento Agentic OMO

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  - type: rpm-ostree
    install:
      - nodejs
      - npm


  - type: files
    files:
      - usr: /usr
