name: bluebuild
on:
  push:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    name: Build Nexus OS
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalar BlueBuild CLI
        run: |
          wget -qO- https://blue-build.org/install.sh | bash

      - name: Build and Push Image
        run: |
          # Compila o sistema operacional burlado a exigencia de assinatura
          /usr/local/bin/bluebuild build --no-sign --push recipe.yml
